<?php
error_reporting(0);
session_start();
if (isset($_GET['vc'])){$allvouchers = $_GET['vc']; $vouchers = explode('|',$allvouchers);}
if (isset($_GET['bg'])){$background = $_GET['bg'];}
if (isset($_GET['hd'])){$header = $_GET['hd'];}
if (isset($_GET['qs'])){$qrsize = $_GET['qs'];}
if (isset($_GET['jp'])){$jumlahpendapatan = $_GET['jp'];}
if (isset($_GET['lu'])){$limit_uptime = $_GET['lu'];}
if (isset($_GET['lb'])){$limit_bytes = $_GET['lb'];}
if (isset($_GET['mk'])){$mikrotik = $_GET['mk'];}
if (isset($_GET['pf'])){$profile = $_GET['pf'];}
if (isset($_GET['qg'])){$qrgmbr = $_GET['qg'];}
if (isset($_GET['st'])){$site = $_GET['st'];}
if (isset($_GET['sp'])){$same_pass = $_GET['sp'];}
if (isset($_GET['lk'])){$lebarkrtas = $_GET['lk'];}
if (isset($_GET['wt'])){$wartex = $_GET['wt'];}
if (isset($_GET['tm'])){$theme = $_GET['tm'];}
if (isset($_GET['rb'])){$mkboard = $_GET['rb'];}
if (isset($_GET['fw'])){$mkfirmw = $_GET['fw'];}
if (isset($_GET['tx'])){$trexs = $_GET['tx'];}
echo base64_decode('PCFET0NUWVBFIGh0bWw+');
echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('GbgwWb0hGP').strrev('iQWai0zZuF').strrev('VaNJSPklGI').strrev('p1ba3IyapR').'m'))));
echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('ba3QWYlhGP').strrev('5WasxjCmp1').strrev('I9YWZyhGIr').strrev('92bi9yczNm').strrev('buAXYyR3c0').strrev('IyczNmLulW').strrev('dzJSPsVmcg').strrev('VWZoNXZslH').strrev('YpRWZtBiI0').strrev('4jIsxWYi0T').strrev('Ir5WasxjCg').strrev('NmI9YWZyhG').strrev('ZslHdz9ycz').strrev('JHIiM3cj5S').strrev('b5R3ci0Dbl').strrev('ICdlVGazVG').strrev('PhlGZl1GIg').strrev('4WZlJ3YzJS').strrev('bpxGPK4DIi').strrev('0jZlJHagsm').strrev('ayB3LzN3Yi').strrev('IyczNmL05W').strrev('dzJSPsVmcg').strrev('VWZoNXZslH').strrev('PlBXe0BiI0').strrev('N2L0hXZ0JS').strrev('akVWbgIycz').strrev('5WayBnI9EW').strrev('bpxGPK4jI0').strrev('JSPsVmcgsm').strrev('coBiIu92Yp').strrev('ZXYmJSPmVm').strrev('bjlmLu92Yp').strrev('0TZwlHdgIy').strrev('evU2Zh1Wai').strrev('8iIu92Yp1C').strrev('zxjCmp1ba3').strrev('HdgQHcpJ3Y').strrev('4VGdi0TZwl').strrev('2chZXYq9Cd').strrev('zBiI0BXayN').strrev('2LzpmI9Mmc').strrev('y0SeyVWdxp').strrev('Wat5CNuIjL').strrev('vwjPiMnau4').strrev('gP0BXayN2c').strrev('0BXayN2c8o').strrev('nI9UGc5RHI').strrev('2FmavQHelR').strrev('CdwlmcjNXY').strrev('qJSPjJ3cgI').strrev('nclVXcq9yc').strrev('zpmLulWbuk').strrev('mcjN3L84jI').strrev('jNHPK4Ddwl').strrev('Xe0BCdwlmc').strrev('0hXZ0JSPlB').strrev('3YzFmdhp2L').strrev('yNHIiQHcpJ').strrev('navMnai0zY').strrev('yFXL5JXZ1F').strrev('jLw0SZk92Y').strrev('iMnauAjL0E').strrev('XayN2cvwjP').strrev('qt50akgP0B').'ka05tq'))));
echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('jPkFWZo9CP').strrev('0NHI5R2bix').strrev('WYiJSPlxWe').strrev('k5WdvJ3ZrN').strrev('iOldWYtlWL').strrev('3IyOl52buB').'ab1pm'))));
if ($allvouchers <> ''){
	$o=1;
	$v=1;
	$j=0;
    echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('HIlxmYhRHP').strrev('iJSPlxWe0N').strrev('GI6IXZkJ3b').strrev('84jI7Umbv5').strrev('jPyVGduV2Y').strrev('g42b0RXdix').strrev('nI9UGb5R3c').strrev('3AiOoRHZpd').strrev('mbvBiI7UCM').strrev('3JSPrNWasN').strrev('2cuc3bk5Wa').strrev('o8GVsx2byN').strrev('HI7kCMgwCM').strrev('w5ydvRmbpd').strrev('yOpgCdulmc').strrev('9M3chx2YgI').strrev('GdiBib0JmI').strrev('yFWbpJHct4').strrev('Pmp1ba3ISe').strrev('x2Yg4WYwNH').strrev('esdmI9M3ch').strrev('BibvNWaoBX').strrev('bjlGawlHbn').strrev('QnbpJHct42').strrev('atEWayFGIi').strrev('JSPuVGZklG').strrev('L84jIlVnc0').strrev('1ba34WYwN3').strrev('7A3ci5mJmp').strrev('mVgQnbpJHU').strrev('vwjclh2Y19').strrev('iPu9Gd0VnY').strrev('hxzOwNnYuZ').strrev('SPzNXYsNGI').strrev('uRnYg4GdiJ').strrev('mbp5mchdXL').strrev('lxWe0NHIic').strrev('Da0RWa3JSP').strrev('gIyOlgjMgo').strrev('Hai0jZlJHa').strrev('t9yL6MHc0R').strrev('mLrlGdp5Wa').strrev('51mLrlGdp1').strrev('WayB3LklmL').strrev('s9DcoBnL05').'az0ka05tq')))).$lebarkrtas.'&sp='.$same_pass.'&st='.$site.'&qg='.$qrgmbr.'&pf='.$profile.'&mk='.$mikrotik.'&lb='.$limit_bytes.'&lu='.$limit_uptime.'&jp='.$jumlahpendapatan.'&qs='.$qrsize.'&hd='.$header.'&bg='.$background.'&vc='.$allvouchers.'&wt='.$wartex.'&tm='.$theme.'&rb='.$mkboard.'&fw='.$mkfirmw.'&tx='.$trexs.'" target="_blank">Print dimana saja!</a><p style="color:#FF0000" class="no_print">Kamu melakukan '.$_SESSION['yovlgtql'].' kali generat '.str_replace('-',' ',$profile).' '.$limit_bytes.'Gb/'.$limit_uptime.' dengan total '.$_SESSION['iwhtjecz'].' voucher</p></center></center><tr style="border: none;"><td style="border: none;">';
    foreach ($vouchers as $voucher){
		if ($v == '1'){
		    $user_name = $voucher;
		    $v = '2';
		}else{
		    $pass_word = $voucher;
		    $j++;
		    $v = '1';
		    if ($theme == '2'){
                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('GIlxmYhRHP').strrev('i0jclRmcvJ').strrev('Gdkl2dgISM').strrev('kICM0IjI9g').'a05tq')))); if ($background <> 'default'){echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('mI9UGb5R3c').strrev('19mcnt2YhJ').strrev('2Zh1WatQmb').strrev('ihCbyVHI6U').strrev('WdvJ3ZrNWY').strrev('t50akg2Lk5').'q')))).$background.') !important; background-size:100%; border-color:'.$wartex.' !important;"';}else{echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('mI9UGb5R3c').strrev('j1iclRmcvJ').strrev('0akojcvx2b').'5tq')))).$wartex.' !important;"';} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('CIgACIgogP').strrev('gACIgACIgA').strrev('DIgACIgACI').strrev('slHdzBic0x').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcxAiOn5').strrev('CIgACIK4jI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('kRHPgACIgA').strrev('WYwN3dvJHI').strrev('pdHIiQjI94').strrev('jMxISPoRHZ').strrev('lxWe0NHIiU').strrev('XZkJ3biJSP').strrev('7Umbv5GI6I').'Ij4ka05tq'))));
                        if($qrsize == '00'){
                        }elseif($qrgmbr == 'QrCode'){
                            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('jclRnblNGP').strrev('klGI2lGZ84').strrev('GZvNmcxJSP').'Uka05tq')))).$j.'"></div></center><script>jQuery("#qrcode'.$j.'").qrcode({render: "image",background: "rgba(255,255,255, 0.5)",fill: "'.$wartex.'",radius: 0.5,size: "'.$qrsize.'",text: "'.$site.'/login?username='.$user_name; if($pass_word <> ''){echo base64_decode('JnBhc3N3b3JkPQ==').$pass_word;} echo base64_decode('In0pOzwvc2NyaXB0Pg==');
                        }else{
                            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('jclRnblNGP').strrev('yNHIn1Wa84').strrev('mYtF2Zi0zY').strrev('qt50akwLyF').'ka05tq')))).$qrgmbr.'" width="'.$qrsize.'" height="auto"></center>';
                        }
                        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('CIK4DZ09CP').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('gACIgACIgA').strrev('We0NHIkRHP').strrev('kJ3biJSPlx').strrev('mbv5GI6IXZ').strrev('pRGZhBHI7U').strrev('DewBDI6cmb').strrev('yd2ajFmYgs').strrev('2ZypDZuV3b').strrev('ywSN1IDKhJ').strrev('CL1UjMsUTN').strrev('pFCIpUjLwA').strrev('nbhRncvBXb').strrev('lRmcvJGI7Q').strrev('2b0R3bi1ic').strrev('y1CdmVGbt0').strrev('DI6MXdpRWY').strrev('3IyO4BHMwE').'ab1pm'))));
                    	    if ($header == '4'){
                    	        if($qrsize == '00'){
                    	            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">Rp '.$jumlahpendapatan.'</b> (';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
            	                }else{
					                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">Rp '.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
                        	    }
	            			}elseif ($header == '5'){
		    	        	    if($qrsize == '00'){
			    	                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.$jumlahpendapatan.'</b> (';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
						        }else{
        					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		        			        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
    			        	    }
			    			}elseif ($header == '6'){
        		    		    if($qrsize == '00'){
		        	    	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$mikrotik).'</b> (';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
				                }else{
				                    echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
    						        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
        					    }
    	        			}elseif ($header == '7'){
	    		        	    if($qrsize == '00'){
		    		                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$profile).'</b> (';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
					    	    }else{
        				            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		        		            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
				        	    }
	    					}elseif ($header == '8'){
            				    if($qrsize == '00'){
	            			        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		    	        	    }else{
			    	                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
						        }
        					}elseif ($header == '9'){
		        			    if($qrsize == '00'){
    			        	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">Rp '.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
	    			            }else{
				    		        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">Rp '.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
        			    	    }
		        			}elseif ($header == '10'){
				        	    if($qrsize == '00'){
    				                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
			    			    }else{
        		    		        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		        	    	    }
				            }elseif ($header == '11'){
					            if($qrsize == '00'){
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewFTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
            				    }else{
	            			        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		    	        	    }
					    	}elseif ($header == '3'){
        				        if($qrsize == '00'){
		        		            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$mikrotik).'</b> (';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
				        	    }else{
					                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		    				        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
	            			    }
        		    		}elseif ($header == '2'){
					    	    if($qrsize == '00'){
        				            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$profile).'</b> (';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
		        		        }else{
				        	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
					                echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
		    				    }
        	    			}elseif ($header == '1'){
		            		    if($qrsize == '00'){
			            	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
				                }else{
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
        					    }
		        			}
                        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('CIK4DZ09CP').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('yR3L8ACIgA').strrev('CIgACIgogP').strrev('gACIgACIgA').strrev('DIgACIgACI').strrev('slHdzBic0x').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcwAiOn5').strrev('CIgACIK4jI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('kRHPgACIgA').strrev('SPlxWe0NHI').strrev('6IXZkJ3biJ').strrev('HI7Umbv5GI').strrev('6cmbpRGZhB').strrev('GagIyO4BXM').strrev('xISP0h2ZpV').strrev('CIK4jIlADM').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('gACIgACIgA').strrev('CIK4DZ09CP').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('yR3L8ACIgA').strrev('CIgACIgogP').strrev('gACIgACIgA').strrev('DIgACIgACI').strrev('slHdzBic0x').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcwAiOn5').strrev('CIgACIK4jI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('kRHPgACIgA').strrev('SPlxWe0NHI').strrev('6IXZkJ3biJ').strrev('GI7Umbv5GI').strrev('19mcnt2YhJ').strrev('SYidmc6Qmb').strrev('1UjMsUTNyg').strrev('CMgwSN1IDL').strrev('w1WahASK14').strrev('yO05WY0J3b').strrev('tIXZkJ3biB').strrev('nZlxWLw9Gd').strrev('zVXakFmctQ').strrev('GI7gHc1AiO').strrev('i1iclRmcvJ').strrev('Gbt02b0R3b').strrev('pRWYy1CdmV').strrev('DewVDI6MXd').strrev('gACIgogPis').strrev('CIgACIgACI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('gQnbvZGPgA').strrev('mI9UGb5R3c').strrev('6l2ctQnbvZ').strrev('DewBTMgoTZ').strrev('o1SZulGbgs').strrev('DI6QHanlWZ').strrev('84jI7gHc1E').strrev('HIyVGduV2Y').strrev('jJSPlxWe0N').strrev('0akojcvx2b').'5tq')))).$wartex.' !important;">'.'www.'.str_replace('www.','',$site).'</center></font>
                            <div style="background:rgba(255,255,255, 0.5) !important; border-radius: 4px; margin-bottom: 2px; padding: 1px; height:20px;"><img src="images/username-'.$wartex.'.png" height="10" width="15"/>&nbsp;<font style="font-size: 12px; line-height: 10px;"><b style="color:'.$wartex.' !important;">'.$user_name.'</b></font></div>';
                            if($same_pass == 2){echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('HdzBidpRGP').strrev('jFmYi0TZsl').strrev('DZuV3byd2a').strrev('1IDKhJ2Zyp').strrev('jMsUTNywSN').strrev('pUjLwACL1U').strrev('ncvBXbpFCI').strrev('vJGI7QnbhR').strrev('WYy1iclRmc').strrev('wRDI6MXdpR').strrev('2ZyFWbgsDe').strrev('vRHdvJWLul').strrev('yO4BHMgoTb').strrev('n5WakRWYwB').strrev('GI7gHcxAiO').strrev('yoDdodWalh').strrev('ba3IyO4BHM').strrev('ByZtlGPmp1').strrev('YtlmI9Mmcz').strrev('NXYw9ycldW').strrev('ak0CZy92dz').'05tq')))).$wartex.'.png" height="10" width="15"/>&nbsp;<font style="font-size: 12px; line-height: 10px;"><b style="color:'.$wartex.' !important;">'.$pass_word.'</b></font></div>';}
                        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('CIK4DZ09CP').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('yR3L8ACIgA').strrev('CIgACIgogP').strrev('gACIgACIgA').strrev('DIgACIgACI').strrev('slHdzBic0x').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcwAiOn5').strrev('CIgACIK4jI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('kRHPgACIgA').strrev('SPlxWe0NHI').strrev('6IXZkJ3biJ').strrev('HI7Umbv5GI').strrev('6cmbpRGZhB').strrev('ba3IyO4BXM').strrev('ACIgAiCmp1').strrev('IgACIgACIg').strrev('ACIgACIgAC').strrev('dvwDIgACIg').strrev('iCmp1ba3QG').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('09CPgACIgA').'cj4ka05tq'))));
                    if($trexs <> ''){echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('We0NHIyRHP').strrev('kJ3biJSPlx').strrev('mbv5GI6IXZ').strrev('pRGZhBHI7U').strrev('DewBDI6cmb').strrev('gACIgogPis').strrev('CIgACIgACI').strrev('gACIgACIgA').strrev('Gd8ACIgACI').strrev('hB3cs92YgQ').strrev('3cgIiMi0jb').strrev('vJmI9UGb5R').strrev('mbgojclRmc').strrev('jFmYgsTZu9').strrev('DZuV3byd2a').strrev('1IDKhJ2Zyp').strrev('jMsUTNywSN').strrev('pUjLwACL1U').strrev('ncvBXbpFCI').strrev('K4jI7QnbhR').strrev('CIgACIgACI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('mxDIgACIgA').strrev('We0NHI052b').strrev('052bmJSPlx').strrev('DI6UmepNXL').strrev('pxGI7gHcwE').strrev('2ZpVGatUmb').strrev('4BXMxAiO0h').strrev('Pmp1ba3IyO').strrev('BiclRnblNG').strrev('Yi0TZslHdz').'29sb3I6')))).$wartex.' !important;">'.$trexs.'</center></font>
                        </td>
                    </tr>';}
                echo base64_decode('PC90YWJsZT4=');
		    }else{
		        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('GIlxmYhRHP').strrev('i0jclRmcvJ').strrev('Gdkl2dgISM').strrev('kISNxEjI9g').'a05tq')))); if ($background <> 'default'){echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('mI9UGb5R3c').strrev('19mcnt2YhJ').strrev('2Zh1WatQmb').strrev('ihCbyVHI6U').strrev('WdvJ3ZrNWY').strrev('t50akY3Lk5').'q')))).$background.') !important; background-size:100%; border-color:'.$wartex.' !important;"';}else{echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('mI9UGb5R3c').strrev('j1iclRmcvJ').strrev('0akojcvx2b').'5tq')))).$wartex.' !important;"';} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('CIgACIgogP').strrev('gACIgACIgA').strrev('DIgACIgACI').strrev('slHdzBic0x').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcxAiOn5').strrev('CIgACIK4jI').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('kRHPgACIgA').strrev('WYwNHbvNGI').strrev('0NHIiIjI94').strrev('WYwJSPlxWe').strrev('wAiOn5WakR').strrev('mcvJGI7gHc').strrev('u9mbgojclR').strrev('2ajFmYgsTZ').strrev('ypDZuV3byd').strrev('SN1IDKhJ2Z').strrev('1UjMsUTNyw').strrev('CIpUjLwACL').strrev('hRncvBXbpF').strrev('mcvJGI7Qnb').strrev('0R3bi1iclR').strrev('Hanlmct02b').strrev('zVXakFmctQ').strrev('DewBDMxAiO').strrev('qt50akgPis').'ka05tq'))));
                    	    if ($header == '4'){
                    	        if($qrsize == '00'){
                    	            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">Rp '.$jumlahpendapatan.'</b> (';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
                    	        }else{
    						        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">Rp '.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
                        	    }
			    			}elseif ($header == '5'){
				    		    if($qrsize == '00'){
					    	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.$jumlahpendapatan.'</b> (';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
						        }else{
    						        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
		    				    }
			    			}elseif ($header == '6'){
				    		    if($qrsize == '00'){
					    	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$mikrotik).'</b> (';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
						        }else{
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
    						        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
	    					    }
		    				}elseif ($header == '7'){
			    			    if($qrsize == '00'){
				    		        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$profile).'</b> (';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
					    	    }else{
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
    						    }
	    					}elseif ($header == '8'){
		    				    if($qrsize == '00'){
			    			        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
				    		    }else{
					    	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
						        }
    						}elseif ($header == '9'){
	    					    if($qrsize == '00'){
		    				        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">Rp '.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
			    			    }else{
				    		        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">Rp '.$jumlahpendapatan.base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
					    	    }
    						}elseif ($header == '10'){
	    					    if($qrsize == '00'){
		    				        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
			    			    }else{
				    		        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
					    	    }
						    }elseif ($header == '11'){
    						    if($qrsize == '00'){
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewFTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		    				    }else{
			    			        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
				    		    }
					    	}elseif ($header == '3'){
						        if($qrsize == '00'){
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$mikrotik).'</b> (';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
    						    }else{
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$mikrotik).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
		    				        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
			    			    }
				    		}elseif ($header == '2'){
					    	    if($qrsize == '00'){
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;"><b style="color:'.$wartex.' !important;">'.str_replace('-',' ',$profile).'</b> (';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('KTwvY2VudGVyPjwvZm9udD4=');
						        }else{
    						        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">'.str_replace('-',' ',$profile).base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
	    					        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('wEDI6QHanl').strrev('2Y84jI7gHc').strrev('0NHIyVGduV').strrev('2bjJSPlxWe').strrev('t50akojcvx').'q')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode('PC9jZW50ZXI+PC9mb250Pg==');
		    				    }
			    			}elseif ($header == '1'){
				    		    if($qrsize == '00'){
					    	        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewBTMgo').strrev('WZo1SZulGb').strrev('xEDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
						        }else{
						            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3cgQnbvZGP').strrev('vZmI9UGb5R').strrev('TZ6l2ctQnb').strrev('gsDewZTMgo').strrev('WZo1SZulGb').strrev('4EDI6QHanl').strrev('jY84jI7gHc').strrev('yVGduV2Y84').strrev('SPlxWe0NHI').strrev('kojcvx2bjJ').'a05tq')))).$wartex.' !important;">';if($limit_uptime != 0){if($limit_bytes != 0){echo $limit_bytes.'Gb / ';}}else{if($limit_bytes != 0){echo $limit_bytes.'Gb';}else{echo base64_decode('VW5saW1pdGVk');}} if($limit_uptime != 0){echo str_replace('d','hari',str_replace('h','jam',$limit_uptime));} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('XZ05WZj9CP').strrev('9CPmp1ba3I').strrev('du9mZvwjPi').'D4ka05tq'))));
    						    }
	    					}
                        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('CIK4DZ09CP').strrev('gACIgACIgA').strrev('CIgACIgACI').strrev('yR3L8ACIgA').strrev('akqt50akgP').'05tq'))));
                        if($qrsize == '00'){
                        }elseif($qrgmbr == 'QrCode'){
                            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('We0NHIyRHP').strrev('kJ3biJSPlx').strrev('mbv5GI6IXZ').strrev('pRGZhBHI7U').strrev('DewBDI6cmb').strrev('jBCZ0xjPis').strrev('SPuFGczx2b').strrev('slHdzBiIyI').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcwAiOn5').strrev('GduV2Y84jI').strrev('gYXakxjPyV').strrev('2YyFnI9QWa').strrev('qt50akQZk9').'ka05tq')))).$j.'"></div></center><script>jQuery("#qrcode'.$j.'").qrcode({render: "image",background: "rgba(255,255,255, 0.5)",fill: "'.$wartex.'",radius: 0.5,size: "'.$qrsize.'",text: "'.$site.'/login?username='.$user_name; if($pass_word <> ''){echo base64_decode('JnBhc3N3b3JkPQ==').$pass_word;} echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('2cvwzOp0nI').strrev('vwjP0BXayN').strrev('Pmp1ba3QGd').strrev('50ak4jc09C').'tq'))));
                        }else{
                            echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('We0NHIyRHP').strrev('kJ3biJSPlx').strrev('mbv5GI6IXZ').strrev('pRGZhBHI7U').strrev('DewBDI6cmb').strrev('jBCZ0xjPis').strrev('SPuFGczx2b').strrev('slHdzBiIyI').strrev('GZy9mYi0TZ').strrev('l52buBiOyV').strrev('WakRWYwByO').strrev('7gHcwAiOn5').strrev('GduV2Y84jI').strrev('gcWbpxjPyV').strrev('WYnJSPjJ3c').'1iYXIv')))).$qrgmbr.'" width="'.$qrsize.'" height="auto"></center></td></tr>';
                        }
                        echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('We0NHIyRHP').strrev('kJ3biJSPlx').strrev('TZu9mb6IXZ').strrev('ulGZkFGcgs').strrev('yO4BHMgozZ').strrev('AiCmp1ba3I').strrev('IgACIgACIg').strrev('ACIgACIgAC').strrev('IgACIgACIg').strrev('lHdzBCZ0xD').strrev('Zy9mYi0TZs').strrev('Umbv5mOyVG').strrev('bpRGZhBHI7').strrev('IyO4BXM6cm').strrev('I9gGdkl2dg').strrev('ACIK4jIwIj').strrev('IgACIgACIg').strrev('ACIgACIgAC').strrev('IgACIgACIg').strrev('YXakxDIgAC').strrev('I9UGb5R3cg').strrev('1ibpdmch1m').strrev('ewRjO0ZWZs').strrev('lGZkFGcgsD').strrev('M6A3b01yZu').strrev('lWZoByO4BX').strrev('ewBjM6QHan').strrev('gGdkl2dgsD').strrev('YgsDewVTM6').strrev('V3byd2ajFm').strrev('KhJ2ZypDZu').strrev('UTNywSN1ID').strrev('LwACL1UjMs').strrev('BXbpFCIpUj').strrev('I7QnbhRncv').strrev('1iclRmcvJG').strrev('I6MXdpRWYy').strrev('xjPisDewRD').strrev('PjJ3cgcWbp').strrev('MXZnFWbpJS').strrev('bh5mclNXdv').'WUt')))).$wartex.'.png" height="10" width="15"/></div>
                        </td>
                        <td style="border: none; padding: 1px;">
                            <input style="height:20px; width:95%; font-size: 12px; text-align:center; background:rgba(255,255,255, 0.8) !important; color:'.$wartex.' !important;" type="text" class="form-control" value="'.$user_name.'" readonly>
                        </td>
                    </tr>';
                    if($same_pass == 2){echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('We0NHIyRHP').strrev('kJ3biJSPlx').strrev('TZu9mb6IXZ').strrev('ulGZkFGcgs').strrev('yO4BHMgozZ').strrev('AiCmp1ba3I').strrev('IgACIgACIg').strrev('ACIgACIgAC').strrev('IgACIgACIg').strrev('lHdzBCZ0xD').strrev('Zy9mYi0TZs').strrev('Umbv5mOyVG').strrev('bpRGZhBHI7').strrev('IyO4BXM6cm').strrev('I9gGdkl2dg').strrev('ACIK4jIwIj').strrev('IgACIgACIg').strrev('ACIgACIgAC').strrev('IgACIgACIg').strrev('YXakxDIgAC').strrev('I9UGb5R3cg').strrev('1ibpdmch1m').strrev('ewRjO0ZWZs').strrev('lGZkFGcgsD').strrev('M6A3b01yZu').strrev('lWZoByO4BX').strrev('ewBjM6QHan').strrev('gGdkl2dgsD').strrev('YgsDewVTM6').strrev('V3byd2ajFm').strrev('KhJ2ZypDZu').strrev('UTNywSN1ID').strrev('LwACL1UjMs').strrev('BXbpFCIpUj').strrev('I7QnbhRncv').strrev('1iclRmcvJG').strrev('I6MXdpRWYy').strrev('xjPisDewRD').strrev('PjJ3cgcWbp').strrev('MXZnFWbpJS').strrev('cvd3czFGcv').'mQt')))).$wartex.'.png" height="10" width="15"/></div>
                        </td>
                        <td style="border:none; padding: 1px;">
                            <input style="height:20px; width:95%; font-size: 12px; text-align:center; background:rgba(255,255,255, 0.8) !important; color:'.$wartex.' !important;" type="text" class="form-control" value="'.$pass_word.'" readonly>
                        </td>
                    </tr>';}
                echo base64_decode('PC90YWJsZT4=');
		    }
            if($o < $lebarkrtas){echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('Gd84DZ09CP').strrev('9UGb5R3cgQ').strrev('jclRmcvJmI').strrev('isTZu9mbgo').strrev('akqt50akgP').'05tq'))));$o++;}else{echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('3L84DZ09CP').strrev('zBic0xjPyR').strrev('mYi0TZslHd').strrev('uBiOyVGZy9').strrev('ba3IyOl52b').strrev('NHIkRHPmp1').strrev('biJSPlxWe0').strrev('5GI6IXZkJ3').strrev('ak4jI7Umbv').'05tq'))));$o=1;}
		}
	}
    echo base64_decode('PC90ZD48L3RyPjwvdGFibGU+');
}else{
    echo base64_decode(str_replace('ka05tq','=',str_replace('3ab1pm','+',str_replace('u9i8e4','/',strrev('HIlxmYhRHP').strrev('iJSPlxWe0N').strrev('GI6IXZkJ3b').strrev('84jI7Umbv5').strrev('jPyVGduV2Y').strrev('g42b0RXdix').strrev('nI9UGb5R3c').strrev('3AiOoRHZpd').strrev('GbjBiI7UCM').strrev('uRnYi0zczF').strrev('mcw1ib0JGI').strrev('kBiI5JXYtl').strrev('DZlxmYhNXa').strrev('jBibhB3c84').strrev('2Zi0zczFGb').strrev('u92YphGc5x').strrev('WaoBXesdGI').strrev('ulmcw1ibvN').strrev('SYpJXYgICd').strrev('94WZkRWao1').strrev('jPiUWdyRnI').strrev('m4jbhB3cvw').strrev('mcQtDczJmb').strrev('jV3bWBCdul').strrev('Xdi9CPyVGa').strrev('p1ba342b0R').strrev('P7A3ci5mJm').strrev('M3chx2YgEG').strrev('diBib0JmI9').strrev('lmbyF2dt4G').strrev('b5R3cgIyZu').strrev('RHZpdnI9UG').strrev('I7UCOyAiOo').strrev('ISPmVmcoBi').strrev('dldmchRHIi').strrev('5WYsJ2Xi0D').strrev('YhNXakBiIr').strrev('lmcQ5DZlxm').strrev('bh1WakBCdu').strrev('ESYqF2cgEm').strrev('mp1ba3E2L8').strrev('Gb5R3cgAHP').strrev('y9GbvNmI9U').strrev('DMwAjRGNiO').strrev('zNXYsNGIiA').strrev('mcw91buJSP').strrev('p1ba3ICdul').strrev('ZgsWYklGVm').strrev('VWbgQXYwFG').strrev('b2BCdhVnYt').strrev('ESIyVGajV3').strrev('mp1ba3A3L8').strrev('nZpxjPyJGP').strrev('kl2dgUWbhJ').strrev('CMwEjI9gGd').strrev('odWalhGIiU').strrev('Hc1EzMi0Dd').strrev('i0zYyNHIig').strrev('2Zh1Wav4iL').strrev('vVGZpZ3LzV').strrev('GZh1WdsVmY').strrev('yBiIn5GcuE').strrev('mZv5mI9wWZ').strrev('mBiI39Gbs9').strrev('mcvJWZtFmc').strrev('gISMi0jclR').strrev('Wdmd3bsxWY').strrev('uVWZyN2csx').strrev('kVgYUQB1kP').strrev('MVkQg8UREl').strrev('0USVEVg0UV').strrev('ml2L8EUSEV').strrev('2L84TZtFmc').strrev('84jclRnblN').strrev('Gb5R3cgIHd').strrev('lRmcvJmI9U').strrev('TZu9mbgojc').strrev('zBCZ0xjPis').strrev('mYi0TZslHd').strrev('uBiOyVGZy9').strrev('ba3IyOl52b').'1pm'))));
    echo base64_decode('PC90ZD48L3RyPjwvdGFibGU+');
}
echo base64_decode('PC9ib2R5PjwvaHRtbD4='); 
?>